[project]
# Set the build directory to your server folder
build_dir = "server"

[phases.setup]
packages = ["nodejs", "npm"]  # install Node and npm

[phases.build]
command = "npm install && npm install -g tsx"

[phases.start]
command = "tsx src/index.ts"
