[project]
build_dir = "server"

[phases.setup]
packages = ["nodejs", "npm"]

[phases.build]
command = "npm install && npm install tsx --save-dev"

[phases.start]
command = "./node_modules/.bin/tsx src/index.ts"
